### PR TITLE
Add retries to db connectivity

### PR DESCRIPTION
**Pull request by chashikajw**
## Purpose
This will add retries to create the DB connectivity.

## Fixes
- https://github.com/wso2/apk/issues/869

### CODE REVIEW

**Comment by tharindu1st** [comment]
@chashikajw  Didn't this handle from the ballerina library?. Can you check

**Comment by chashikajw** [comment]
> @chashikajw Didn't this handle from the ballerina library?. Can you check

Seems there is a configuration related to this. I will check and apply that.

**Comment by chashikajw** [comment]
> @chashikajw Didn't this handle from the ballerina library?. Can you check

Retries are not supported by the client itself

**Comment by chashikajw** [comment]
Closing the PR since this is handled by initContainer[1].

[1] https://github.com/wso2/apk/pull/259

**Pull request closed without merging**
